resources:
- ../../base
patches:
- path: workers.yaml
- path: importer.yaml
- path: importer-deleter.yaml
- path: exporter.yaml
- path: alpine-cve-convert.yaml
- path: debian-cve-convert.yaml
- path: combine-to-osv.yaml
- path: debian-convert.yaml
- path: debian-first-version.yaml
- path: debian-copyright-mirror.yaml
- path: cpe-repo-gen.yaml
- path: nvd-cve-osv.yaml
- path: nvd-mirror.yaml
- path: relations.yaml
- path: backup.yaml
- path: generate-sitemap.yaml
- path: recoverer.yaml
- path: record-checker.yaml
- path: cve5-to-osv.yaml
- path: custommetrics.yaml

