resources:
- ../../base
- make-bugs-public.yaml
- process-results.yaml
patches:
- path: workers.yaml
- path: importer.yaml
- path: exporter.yaml
- path: alpine-cve-convert.yaml
- path: debian-cve-convert.yaml
- path: combine-to-osv.yaml
- path: debian-convert.yaml
- path: debian-first-version.yaml
- path: debian-copyright-mirror.yaml
- path: cpe-repo-gen.yaml
- path: nvd-cve-osv.yaml
- path: nvd-mirror.yaml
- path: alias-computation.yaml
- path: backup.yaml
