version: 2
updates:
- package-ecosystem: pip
  directory: "/docker/worker"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/gcp/api"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/gcp/appengine"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/gcp/functions/pypi"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/gcp/appengine/frontend"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/gcp/appengine/frontend3"
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
