steps:
# Checkout at specified commit.
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/google/osv.dev.git']
- name: gcr.io/cloud-builders/git
  args: ['checkout', '$COMMIT_SHA']
  dir: 'osv.dev'
# Apply GKE configs.
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=workers', '--image=gcr.io/oss-vdb/worker:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp', '--timeout=10m0s']
  dir: 'gke'
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=importer', '--image=gcr.io/oss-vdb/importer:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp']
  dir: 'gke'
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=exporter', '--image=gcr.io/oss-vdb/exporter:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp']
  dir: 'gke'
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=alpine-cve-convert', '--image=gcr.io/oss-vdb/alpine-cve-convert:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp']
  dir: 'gke'
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=combine-to-osv', '--image=gcr.io/oss-vdb/combine-to-osv:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp']
  dir: 'gke'
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=debian/debian-convert.yaml', '--image=gcr.io/oss-vdb/debian-convert:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp']
  dir: 'gke'
- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=debian/debian-first-version.yaml', '--image=gcr.io/oss-vdb/debian-convert:$COMMIT_SHA', '--location=us-central1-f', '--cluster=workers', '--output=/tmp']
  dir: 'gke'
# TODO(ochang): Debian, indexer.
# TODO(ochang): API deployment
timeout: 2400s
serviceAccount: 'projects/oss-vdb-test/serviceAccounts/deployment@oss-vdb-test.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: N1_HIGHCPU_8
tags:
- prod-deploy
