apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: exporter
            image: exporter
            imagePullPolicy: Always
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            args:
              # TODO(michaelkedar): single source of truth w/ terraform config
              - "--bucket=osv-test-vulnerabilities"
            volumeMounts:
              - mountPath: "/work"
                name: "ssd"
            resources:
              requests:
                cpu: 1
                memory: "3G"
              limits:
                cpu: 1
                memory: "4G"
          restartPolicy: OnFailure
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
