[project]
name = "debian_converter" 
requires-python = ">=3.11,<4.0"
dependencies = [
    "markdownify==0.14.1",
    "pandas==2.2.3",
    "python-dateutil==2.9.0.post0",
]
dynamic = ["version"]

[tool.poetry]
package-mode = false 

[tool.poetry.group.dev.dependencies] 
yapf = "*"
pylint = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
