[tool.poetry]
name = "datafix"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

markdownify = "==0.14.1"
pandas = "==2.2.3"
python-dateutil = "==2.9.0.post0"

[tool.poetry.dev-dependencies]
yapf = "*"
pylint = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
