[project]
name = "pypi-publish"
requires-python = ">=3.11,<4.0"
dependencies = [
    "cryptography (==44.0.2)",
    "google-cloud-secret-manager (==2.23.2)",
    "osv (==0.0.22)",
    "requests (==2.32.3)",
]
[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
