[tool.poetry]
name = "pypi-publish"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

cryptography = "==43.0.3"
google-cloud-secret-manager = "==2.20.2"
osv = "==0.0.22"
requests = "==2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
