resources:
- workers.yaml
- scaler.yaml
- importer.yaml
- exporter.yaml
- alpine-cve-convert.yaml
- combine-to-osv.yaml
- debian-convert.yaml
- debian-first-version.yaml
- debian-copyright-mirror.yaml
- cpe-repo-gen.yaml
- nvd-cve-osv.yaml
- alias-computation.yaml
- nvd-mirror.yaml
- backup.yaml