[project]
name = "worker"
requires-python = ">=3.11,<4.0"
dependencies = [
    "google-auth-httplib2==0.2.0",
    "google-api-python-client==2.147",
    "google-cloud-pubsub==2.27.2",
    "google-cloud-ndb==2.3.2",
    "google-cloud-storage==2.19.0",
    "pyyaml==6.0.2",
    "redis==5.2.1",
    "packageurl-python==0.16.0",
    "pygit2==1.17.0",
    "requests==2.32.3",
    "jsonschema==4.23.0",
    "osv @ {path=\"../../\",develop=true}",
]
dynamic = ["version"]

[tool.poetry]
package-mode = false  

[tool.poetry.group.dev.dependencies] 
yapf = "*"
pylint = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"