# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _TERRAFORM_VERSION: 1.3.8
steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
  args:
  - build
  - --build-arg
  - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
  - --tag
  - gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}
  - --tag
  - gcr.io/${PROJECT_ID}/terraform:latest
  - .
- name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  args: ['version']
images:
  - 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  - 'gcr.io/${PROJECT_ID}/terraform:latest'
tags: ['cloud-builders-community']
