[tool.poetry]
name = "api-backend"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

google-cloud-ndb = "==2.3.1"
google-cloud-logging = "==3.10.0"
packageurl-python = "==0.15.1"
packaging = "==20.9"
requests = "==2.32.3"
grpcio = "==1.64.1"
grpcio-reflection = "==1.62.2"
grpcio-health-checking = "==1.62.2"

osv = { path = "../../", develop = true }

[tool.poetry.dev-dependencies]
grpcio-tools = "*"
yapf = "*"
pylint = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
